ข้อมูลสูญหาย(Missing Values)
- การเติมข้อมูล(Imputation)
- การแทนที่(Replace)

1.Import libary and load data

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.impute import SimpleImputer

#load data
df = pd.read_csv('https://raw.githubusercontent.com/zief0002/bespectacled-antelope/main/data/mammals.csv')
df.head()

species  body_weight  brain_weight  slow_wave  paradox  \
0           African elephant     6654.000        5712.0        NaN      NaN   
1  African giant pouched rat        1.000           6.6        6.3      2.0   
2                 Arctic fox        3.385          44.5        NaN      NaN   
3     Arctic ground squirrel        0.920           5.7        NaN      NaN   
4             Asian elephant     2547.000        4603.0        2.1      1.8   

   total_sleep  lifespan  gestation  predation  exposure  danger  
0          3.3      38.6      645.0          3         5       3  
1          8.3       4.5       42.0          3         1       3  
2         12.5      14.0       60.0          1         1       1  
3         16.5       NaN       25.0          5         2       3  
4          3.9      69.0      624.0          3         5       4

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   species       62 non-null     object 
 1   body_weight   62 non-null     float64
 2   brain_weight  62 non-null     float64
 3   slow_wave     48 non-null     float64
 4   paradox       50 non-null     float64
 5   total_sleep   58 non-null     float64
 6   lifespan      58 non-null     float64
 7   gestation     58 non-null     float64
 8   predation     62 non-null     int64  
 9   exposure      62 non-null     int64  
 10  danger        62 non-null     int64  
dtypes: float64(7), int64(3), object(1)
memory usage: 5.5+ KB


2.ตรวจสอบจำนวน Missing Values ในแต่ละคอลัม

In [ ]:
df.isnull().sum()

species          0
body_weight      0
brain_weight     0
slow_wave       14
paradox         12
total_sleep      4
lifespan         4
gestation        4
predation        0
exposure         0
danger           0
dtype: int64

3.เติม missing values ค่าเฉลี่ย(mean)

In [ ]:
df['slow_wave'].fillna(df['slow_wave'].mean(), inplace=True)
#df[slow_wave]=df['slow_wave'].fillna(df['slow_wave'].mean())
df.isnull().sum()

/tmp/ipython-input-14-2415631831.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['slow_wave'].fillna(df['slow_wave'].mean(), inplace=True)


species          0
body_weight      0
brain_weight     0
slow_wave        0
paradox         12
total_sleep      4
lifespan         4
gestation        4
predation        0
exposure         0
danger           0
dtype: int64

4.เติม missing values ด้วยค่ามัธยฐาน(median)

In [ ]:
df['paradox'].fillna(df['paradox'].median(), inplace=True)
df.isnull().sum()

/tmp/ipython-input-15-3112033036.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['paradox'].fillna(df['paradox'].median(), inplace=True)


species         0
body_weight     0
brain_weight    0
slow_wave       0
paradox         0
total_sleep     4
lifespan        4
gestation       4
predation       0
exposure        0
danger          0
dtype: int64

5.เติม missing values ด้วยค่าฐานนิยม(mode)

In [ ]:
df['total_sleep'].fillna(df['total_sleep'].mode()[0], inplace=True) #เลือกค่าที่พบบ่อย คือ index[0]
df.isnull().sum()

/tmp/ipython-input-18-895703562.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['total_sleep'].fillna(df['total_sleep'].mode()[0], inplace=True) #เลือกค่าที่พบบ่อย คือ index[0]


species         0
body_weight     0
brain_weight    0
slow_wave       0
paradox         0
total_sleep     0
lifespan        4
gestation       4
predation       0
exposure        0
danger          0
dtype: int64

6.เติม Missing Values ด้วย SimpleImputer

In [ ]:
imp_mean = SimpleImputer(strategy='mean') #กำหนดกลยุทธ์
imp_mean.fit_transform(df[['lifespan']]) #2D array


array([[ 38.6       ],
       [  4.5       ],
       [ 14.        ],
       [ 19.87758621],
       [ 69.        ],
       [ 27.        ],
       [ 19.        ],
       [ 30.4       ],
       [ 28.        ],
       [ 50.        ],
       [  7.        ],
       [ 30.        ],
       [ 19.87758621],
       [ 40.        ],
       [  3.5       ],
       [ 50.        ],
       [  6.        ],
       [ 10.4       ],
       [ 34.        ],
       [  7.        ],
       [ 28.        ],
       [ 20.        ],
       [  3.9       ],
       [ 39.3       ],
       [ 41.        ],
       [ 16.2       ],
       [  9.        ],
       [  7.6       ],
       [ 46.        ],
       [ 22.4       ],
       [ 16.3       ],
       [  2.6       ],
       [ 24.        ],
       [100.        ],
       [ 19.87758621],
       [ 19.87758621],
       [  3.2       ],
       [  2.        ],
       [  5.        ],
       [  6.5       ],
       [ 23.6       ],
       [ 12.        ],
       [ 20.2       ],
       [ 13

In [ ]:
imp_median = SimpleImputer(strategy='median') #กำหนดกลยุทธ์
imp_median.fit_transform(df[['lifespan']]) #2D array


array([[ 38.6],
       [  4.5],
       [ 14. ],
       [ 15.1],
       [ 69. ],
       [ 27. ],
       [ 19. ],
       [ 30.4],
       [ 28. ],
       [ 50. ],
       [  7. ],
       [ 30. ],
       [ 15.1],
       [ 40. ],
       [  3.5],
       [ 50. ],
       [  6. ],
       [ 10.4],
       [ 34. ],
       [  7. ],
       [ 28. ],
       [ 20. ],
       [  3.9],
       [ 39.3],
       [ 41. ],
       [ 16.2],
       [  9. ],
       [  7.6],
       [ 46. ],
       [ 22.4],
       [ 16.3],
       [  2.6],
       [ 24. ],
       [100. ],
       [ 15.1],
       [ 15.1],
       [  3.2],
       [  2. ],
       [  5. ],
       [  6.5],
       [ 23.6],
       [ 12. ],
       [ 20.2],
       [ 13. ],
       [ 27. ],
       [ 18. ],
       [ 13.7],
       [  4.7],
       [  9.8],
       [ 29. ],
       [  7. ],
       [  6. ],
       [ 17. ],
       [ 20. ],
       [ 12.7],
       [  3.5],
       [  4.5],
       [  7.5],
       [  2.3],
       [ 24. ],
       [  3. ],
       [ 13. ]])

In [ ]:
imp_mode = SimpleImputer(strategy='most_frequent') #กำหนดกลยุทธ์
imp_mode.fit_transform(df[['lifespan']]) #2D array


array([[ 38.6],
       [  4.5],
       [ 14. ],
       [  7. ],
       [ 69. ],
       [ 27. ],
       [ 19. ],
       [ 30.4],
       [ 28. ],
       [ 50. ],
       [  7. ],
       [ 30. ],
       [  7. ],
       [ 40. ],
       [  3.5],
       [ 50. ],
       [  6. ],
       [ 10.4],
       [ 34. ],
       [  7. ],
       [ 28. ],
       [ 20. ],
       [  3.9],
       [ 39.3],
       [ 41. ],
       [ 16.2],
       [  9. ],
       [  7.6],
       [ 46. ],
       [ 22.4],
       [ 16.3],
       [  2.6],
       [ 24. ],
       [100. ],
       [  7. ],
       [  7. ],
       [  3.2],
       [  2. ],
       [  5. ],
       [  6.5],
       [ 23.6],
       [ 12. ],
       [ 20.2],
       [ 13. ],
       [ 27. ],
       [ 18. ],
       [ 13.7],
       [  4.7],
       [  9.8],
       [ 29. ],
       [  7. ],
       [  6. ],
       [ 17. ],
       [ 20. ],
       [ 12.7],
       [  3.5],
       [  4.5],
       [  7.5],
       [  2.3],
       [ 24. ],
       [  3. ],
       [ 13. ]])

In [ ]:
df.isnull().sum()

species         0
body_weight     0
brain_weight    0
slow_wave       0
paradox         0
total_sleep     0
lifespan        4
gestation       4
predation       0
exposure        0
danger          0
dtype: int64

7.เติมค่าSimpleimputerในdataframe

In [ ]:
df['lifespan'] = imp_mean
df.isnull().sum()

species         0
body_weight     0
brain_weight    0
slow_wave       0
paradox         0
total_sleep     0
lifespan        0
gestation       4
predation       0
exposure        0
danger          0
dtype: int64

In [ ]:
df['gestation'] = imp_median
df.isnull().sum()

species         0
body_weight     0
brain_weight    0
slow_wave       0
paradox         0
total_sleep     0
lifespan        0
gestation       0
predation       0
exposure        0
danger          0
dtype: int64